/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ContentBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MailerHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailerPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailerPort": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailerUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Trpc": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ValkeyCache": {
      "engine": string
      "host": string
      "port": number
      "type": "aws.elasticache/serverlessCache.ServerlessCache"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}