export enum KeyPrefix {
	USER = 'user#',
	USER_NAME = 'user#username',
	USER_EMAIL = 'user#email',

	OTP = 'otp#',

	RELATIONSHIP_REQUEST = 'rshipreq#',
	RELATIONSHIP = 'rship#',
	RELATIONSHIP_REQUEST_SENDER = 'rship::sender',
	RELATIONSHIP_REQUEST_RECEIVER = 'rship::receiver',

	AFFIRMATION = 'rship::affirmation#',
	RECEIVED_AFFIRMATION = 'rship::received_affirmation#',

	NOTIFICATION_SUBSCRIBER = 'notification::subscriber#',

	WEBSOCKET_HEARTBEAT = 'ws::heartbeat#',
}

export enum EntityType {
	USER = 'USER',
	OTP = 'OTP',
	RELATIONSHIP_REQUEST = 'RELATIONSHIP_REQUEST',
	RELATIONSHIP = 'RELATIONSHIP',
	AFFIRMATION = 'AFFIRMATION',
	RECEIVED_AFFIRMATION = 'RECEIVED_AFFIRMATION',
	NOTIFICATION_SUBSCRIBER = 'NOTIFICATION_SUBSCRIBER',
	WEBSOCKET_HEARTBEAT = 'WEBSOCKET_HEARTBEAT',
}
