export enum KeyPrefix {
	USER = 'user#',
	USER_NAME = 'user#username',
	USER_EMAIL = 'user#email',

	RELATIONSHIP_REQUEST = 'rshipreq#',
	RELATIONSHIP = 'rship#',
	RELATIONSHIP_REQUEST_SENDER = 'rship::sender',
	RELATIONSHIP_REQUEST_RECEIVER = 'rship::receiver',

	AFFIRMATION = 'rship::affirmation#',
	RECEIVED_AFFIRMATION = 'rship::received_affirmation#',

	MOMENT_DETAILS = 'moment::details#',
	MOMENT_MESSAGE = 'moment::message#',

	SONG_RECOMMENDATION = 'songrec#',

	NOTIFICATION_SUBSCRIBER = 'notification::subscriber#',

	WEBSOCKET_HEARTBEAT = 'ws::heartbeat#',
}

export enum EntityType {
	USER = 'USER',
	RELATIONSHIP_REQUEST = 'RELATIONSHIP_REQUEST',
	RELATIONSHIP = 'RELATIONSHIP',
	AFFIRMATION = 'AFFIRMATION',
	RECEIVED_AFFIRMATION = 'RECEIVED_AFFIRMATION',
	MOMENT_DETAILS = 'MOMENT_DETAILS',
	MOMENT_MESSAGE = 'MOMENT_MESSAGE',
	NOTIFICATION_SUBSCRIBER = 'NOTIFICATION_SUBSCRIBER',
	WEBSOCKET_HEARTBEAT = 'WEBSOCKET_HEARTBEAT',
}
