name: Build

on:
    push:
        branches:
            - 'features/*'
            - 'feature/*'
            - 'patch/*'
            - 'hotfix/*'
            - 'chore/*'
            - 'dev'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            STAGE: ajani
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install Dependencies
              run: |
                  echo "Installing node dependencies..."
                  bun i
            - name: 'Setup Build Cache'
              uses: actions/cache@v3
              with:
                  path: |
                      ${{ github.workspace }}/packages/frontend/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
            - name: Build Project
              run: |
                  bun run build
