name: Build & Deploy

on:
    push:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Staging
        strategy:
            matrix:
                node-version: [20.x]
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install Dependencies
              run: bun i
            - name: Create CDN Key Files
              run: |
                  mkdir -p ./cdn-keys
                  echo "${{ secrets.CDN_PUBLIC_KEY }}" > ./cdn-keys/staging.public_key.pem
                  echo "${{ secrets.CDN_PRIVATE_KEY }}" > ./cdn-keys/staging.private_key.pem
            - name: Building & Deploy Project
              run: |
                  bunx sst deploy --stage=staging
            - name: Run Db Migrations
              run: |
                  cd packages/frontend
                  bun run auth:db:generate -- --stage ajani
                  bun run auth:db:migrate -- --stage ajani
